---
title: "Teaching and Engagement"
---

#### Courses taught at Colorado State University

**GR 100: Introduction to Geography**
Department of Anthropology & Geography, Fall 2021 (2 sections), Spring 2022, Fall 2022. Major geographic themes applied to selected regions; physical environment, human-land relationships, and regional analysis.

**GR 217: Human-Environment Geographies**
Department of Anthropology & Geography, Spring 2022, Fall 2022. Examines human-environment relationships using geographic theories, geographic methods, and empirical evidence. Explores cross-scalar geographic interactions that shape environmental change and emphasizes critical thinking and small group interactions.

**ECOL/GDPE 592: Sustainable Food Systems**  
Graduate Degree Program in Ecology, Spring 2021. Interdisciplinary complexities of food systems, including material flows and sociopolitical contexts of food that are changing in response to global and local challenges. Analysis of strategies for improving the sustainability and resilience of food systems. Primary disciplinary foci include ecology, agronomy, and social sciences.

#### Courses taught at Iowa State University

**WGS 201 Introduction to Women's and Gender Studies**  
Women's and Gender Studies Program, Spring 2019 (2 sections). Contemporary status of women in the U.S. and worldwide from social, economic, historical, political, philosophical and literary perspectives. Analysis of intersection of gender, race, class, and sexuality. Subject matter includes work, health, sexuality, and violence.

**FOR/NREM 452/552: Ecosystem Management**  
Department of Natural Resource Ecology and Management, Spring 2015. Principles of planning, regulating, and decision-making associated with public and private lands, with consideration of forest, grassland, wetland, and freshwater aquatic ecosystems. Integrated natural resources management within ecological, social, economic and policy constraints.

#### Guest lecturer at Colorado State University

**ANTH 571: Anthropology and Global Health**  
CSU Department of Anthropology & Geography, Fall 2022

**SOC 315: Applications of Qualitative Research**  
CSU Department of Sociology, Fall 2020

**ESS 312: Sustainability Science**  
CSU Department of Ecology Science & Sustainability, Spring 2020

#### Guest lecturer at Iowa State University

**WGS 402/502: Advanced Seminar in Feminist Research Methods**  
Women's and Gender Studies Program, Spring 2022

**WGS 402/502: Advanced Seminar in Feminist Research Methods**  
Women's and Gender Studies Program, Spring 2021

**SOC 513: Qualitative Research Methods**  
Department of Sociology, Spring 2018

**WGS 402/502: Advanced Seminar in Feminist Research Methods**  
Women's and Gender Studies Program, Spring 2017

**CRP 383: Theory of the Planning Process**  
Department of Community and Regional Planning, Fall 2016  

**HORT 376: Field Production of Horticultural Crops**  
Department of Horticulture, Fall 2016   

**FOR 451: Forest Resource Economics**  
Department of Natural Resource Ecology and Management, Spring 2014   

**NREM 570: Advanced Decision-Making in Natural Resource Allocation**   
Department of Natural Resource Ecology and Management, Spring 2014  

#### Select educational outreach and engagement

**Prison agriculture in the United States: Mapping the disciplinary lanscapes of racial capitalism.**
CSU GIS Day, 2021.

**Dare to Share Your Garden**  
ISU Extension & Outreach Cass County Spring Garden Seminar, Spring 2017

**Donation Gardening Trainings**  
ISU Extension Master Gardener Program, Summer 2016  

**Food Security in Iowa Immersion Session Leader**  
World Food Prize Iowa Youth Institute, Spring 2016  

**People in Ecosystems/Watershed Integration Public Workshops**  
Co-hosted by Prairie Rivers of Iowa at Des Moines Area Community College, Fall 2015  

**People in Ecosystems/Watershed Integration Class**  
Des Moines Brody Middle School 7th Grade Science, Spring 2015  




